### ISSUE TITLE
OS X and matplotlib

### ISSUE THREAD

**Issue by klieret** [clusterking/clusterking#19]
Thanks to @celis  for reporting this problem which also applies to ``scikit-optimize``:

https://github.com/scikit-optimize/scikit-optimize/issues/637

**Comment by klieret** [comment]
I have removed matplotlib from the default dependencies, so that users have to explicitly specify that they need plotting (or have to install matplotlib by themselves). If they try to plot without having matplotlib, a warning message appears.

I have also added a link to https://matplotlib.org/3.1.0/faq/osx_framework.html to the installation instructions https://clusterking.readthedocs.io/en/latest/installation.html

@celis Does that solve the issue?

**Comment by DavidMStraub** [comment]
FYI, in flavio this is worked around by treating mpl as "extra" dependency:
https://github.com/flav-io/flavio/blob/master/setup.py#L38

**Comment by klieret** [comment]
Thanks @DavidMStraub 

This is what I did as well :)

**Comment by klieret** [comment]
I should really start to add some ``>=`` to most of the requirements though :sweat:

**Comment by celis** [comment]
thks
