### ISSUE TITLE
AttributeError: 'ClusterPlot' object has no attribute 'figsize'

### ISSUE THREAD

**Issue by jasonaebischerGIT** [clusterking/clusterking#34]
```python
dwe.plot_clusters_scatter(['CVL_bctaunutau', 'CSL_bctaunutau']);
```

creates following error:

**Comment by jasonaebischerGIT** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-57-2c54b0dc6f89> in <module>()
----> 1 change_bpmetric('euclidean',0.01).plot_clusters_scatter(['CVL_bctaunutau']);

~/Repositories/clusterking/clusterking/data/data.py in plot_clusters_scatter(self, params, clusters, cluster_column, bpoint_column, legend, max_subplots, max_cols, markers, figsize, aspect_ratio)
    647         cp.fig_base_size = figsize
    648         cp.aspect_ratio = aspect_ratio
--> 649         cp.scatter(params, clusters=clusters)
    650         return cp.fig
    651 

~/Repositories/clusterking/clusterking/plots/plot_clusters.py in scatter(self, cols, clusters, **kwargs)
    479             detected).
    480         """
--> 481         self._setup_all(cols, clusters)
    482 
    483         for isubplot in range(self._nsubplots - int(self.draw_legend)):

~/Repositories/clusterking/clusterking/plots/plot_clusters.py in _setup_all(self, cols, clusters)
    430         self._find_dofs()
    431         self._sample_dofs()
--> 432         self._setup_subplots()
    433 
    434     def _set_fill_colors(self, matrix: np.ndarray) \

~/Repositories/clusterking/clusterking/plots/plot_clusters.py in _setup_subplots(self)
    232             # todo: this is somewhat problematic, because this won't add space
    233             #   for titles etc. Please do this differently
--> 234             "figsize": (self._ncols * self.figsize[0],
    235                         self._nrows * self.figsize[1]),
    236             "squeeze": False,

AttributeError: 'ClusterPlot' object has no attribute 'figsize'

**Comment by klieret** [comment]
Very strange indeed. 

Can you check if this also happens, when you do 

```python
cp = ck.plots.ClusterPlot(d)
cp.scatter(['CVL_bctaunutau', 'CSL_bctaunutau'])
```

**Comment by jasonaebischerGIT** [comment]
Yes, it also happens with this code.

**Comment by klieret** [comment]
What is shown if you type ``cp.figsize??``

**Comment by jasonaebischerGIT** [comment]
Ah, I think I have to reload the jupyter nb, then the it works again..!

**Comment by klieret** [comment]
Great ;) I was already very confused ;)
