### ISSUE TITLE
LaTeX Alias for Wilson coefficients?

### ISSUE THREAD

**Issue by klieret** [clusterking/clusterking#38]
Perhaps there's already name to LaTeX mappings in the Wilson package?

**Comment by DavidMStraub** [comment]
At present the WCxf format only provides LaTeX code for the operators themselves, not for the WC names. In principle it could we added (and that would be useful).

**Comment by klieret** [comment]
Thanks for confirming this @DavidMStraub. Well it would be certainly nice to have the general LaTeX representations directly in the package. For the application here it would be even better to have short versions like ``$\mathcal C_{V_L}$`` (instead of ``CVL_bctaunutau``), because the ``bctaunutau`` part is clear from the context (usually).  But users usually want to fine tweak their labels anyway, so I'm not sure if it is quite worth the effort.

**Comment by klieret** [comment]
Implemented as an additional method e.g. ``Data.configure_variable("q2", axis_label="$q^2$")``
